### ISSUE TITLE
Return and Space keys do not trigger onPress events

### ISSUE THREAD

**Issue by tom-un** [microsoft/react-native-macos#1622]
### Environment

```markdown
react-native -v: 0.68.57-microsoft.0
npm ls react-native-macos: 0.68.57
node -v: v16.17.1
npm -v: 8.15.0
yarn --version: 1.22.19
xcodebuild -version: Xcode 14.1 Build version 14B47b
```

### Steps to reproduce the bug

1. Go to System Settings and enable Keyboard Navigation: 
<img width="827" alt="KeyboardNavigation" src="https://user-images.githubusercontent.com/30053638/210973966-1c8d01a4-2747-4e90-9dee-b4bca00285c5.png">

2. In RNTester, go to the Pressable page

3. Press the Tab key to move the focus ring to a Presable

4. Press Return key or Space bar

### Expected Behavior

Pressing Return or Space should trigger the press of the Pressable

### Actual Behavior

The system Beep chimes and no press event is triggered
![ReturnKeyNOP](https://user-images.githubusercontent.com/30053638/210974259-2447fc11-59f6-42a8-980d-4322ee8f89cd.gif)

### Additional context

This is a regression starting in .68.
.68 introduced the `validKeysDown` prop.  It seems like Touchable and Pressable should have "enter" and "space" on by default.

**Comment by Saadnajmi** [comment]
I actually have a draft PR out for this: https://github.com/microsoft/react-native-macos/pull/1614

However, I think the better long term thing to do is deprecate our 'validKeysDown' prop in favor of 'keyDownEvents', the prop used in React Native Windows for a few reasons:

1) In React Native Windows, all keyboard events are sent to JS. 'keyDownEvents' just specifies which keyboard events should have their native behavior suppressed. This is more flexible to JS developers than our 'validKeysDown' prop where only the events we specify are sent to This difference isn't obvious and leads to bugs like the one here.

2) keyDownEvents is better documented, and the prop that is in the actual apex: https://github.com/microsoft/react-native-windows/blob/main/vnext/proposals/active/keyboard-reconcile-desktop.md

3) The same prop and behavior makes it easier to write cross platform code. I've had a lot of bugs trying to write cross platform keyboard handlers in FluentUI React Native.

I have another draft PR out to switch us to the new prop: https://github.com/microsoft/react-native-macos/pull/1615

Both PRs are on my backlog, and I wasn't any to merge either soon. If this issue is blocking, I can prioritize the first one perhaps.
