### ISSUE TITLE
Merge with React Native

### ISSUE THREAD

**Issue by landsman** [microsoft/react-native-macos#1935]
### Summary

Why does this have to be fork? There is no room to merge it into the main project?

### Motivation

On the first view, I find it unhealthy to use this project. Is there a future? What will be BC breaks in the next months,... a lot of questions.

**Comment by Saadnajmi** [comment]
Hi. We at Microsoft use React Native macOS for a variety of our products, and have _lots_ of React Native developers within our company. I wouldn't be worried about React Native macOS staying supported, as long as React & React Native are supported :) . It would be nice to merge into the main repo, but that's not really something we have 100% control over. In the meantime, I feel we have done a pretty great job at maintaining our fork and keeping up with releases :D 


To get an idea of how much React Native macOS and React Native windows are used, feel free to check out some of our conference talks!
https://www.youtube.com/watch?v=2HNkqKKYAhU (given by yours truly)
https://www.youtube.com/watch?v=r7yKet5dga4

**Comment by landsman** [comment]
It would make sense to me to have an initiative that would spin off React, React Native into an independent non-profit organization. Individual companies that benefit from the code could then contribute to this organization. Was something like that ever on the table, was it discussed, do you know?

I understand the concern that you couldn't control it in this state. The result is a fork on the end when it could be "just" a sub-package using the unified abstraction.

**Comment by kelset** [comment]
hey @landsman - thanks for raising this up. To reply to the last question: conversation of this type have happened many times between us and Meta, but macOS & Windows won't get upstreamed any time soon; Meta's focus for the react-native core GH project is still Android & iOS, as reiterated very recently [in this RFC](https://github.com/react-native-community/discussions-and-proposals/pull/759). That said, we have been having many conversations with Meta and other partners about making all the out-of-tree platforms (think macos, windows, tvos, visionos, etc etc) more consistent/aligned in how they interact with core; but there's nothing to announce on that front yet. Just know that we are actively thinking of this :)

To clear the air a bit on the current status of this repo:
* we are actively maintaining RNmacOS - and while our approach might seem more focused on internal needs due to limited resources, but we strive to balance this with community engagement ([like going to confs!](https://devblogs.microsoft.com/react-native/)) and development.
* not only Microsoft, but also Meta is actively using RNmacOS for core products! You can learn how about how migrating from Electron to RNWindows/RNmacOS has improved their devloop and Facebook Messanger's performances here ➡️  [Christoph Purrer – From Electron to React Native (Chain React 2023)](https://www.youtube.com/watch?v=ChDQZpWQbwk) (and if you check the second talk Saad posted there's a whole lot of MSFT apps using RNmacOS/Windows as well) 
* because RNmacOS is in many ways a classic git fork, it might look like development is not active in the `main` branch: that's mostly caused by the fact that we do keep up with upstream via separate PRs, such as: https://github.com/microsoft/react-native-macos/pull/2013 (as you can see that one has 700+ commits bundled into it!)
* a much better "tell" of how active development is on this platform is the [amount of releases](https://github.com/microsoft/react-native-macos/tags) we do on a regular basis: 11 patches in the last 3 weeks is a very high number, if I can say so myself ;)
* because of the limited funding we have on this project, we do have tradeoffs, and one of them is how much support we can offer to the broader community of developers - this in practise mean that we do not have dedicated "customer support" type of communication channels, and mostly just interact on GH issues when it's a big enough problem that we need to fix it for ourselves as well. I know it's not ideal but it's the best we can do right now.
  * as a sidenote, this in a way is also a door for opportunities: we'd be more than happy to review PRs to help us address outstanding issues and improve the docs 🤗

All of that said - I'm going to close this off because it led some other folks to believe - incorrectly - that RNmacOS is not a priority for us and that it's not in an healthy state. While there's always room to improve, I'd rather folks not get the wrong idea about the state of the project.

I hope that the insights I shared will help change that a bit! :)

**Comment by landsman** [comment]
> It would make sense to me to have an initiative that would spin off React, React Native into an independent non-profit organization.

It is here! https://react.dev/blog/2025/10/07/introducing-the-react-foundation

**Comment by landsman** [comment]
Time to reopen this? :)

**Comment by Saadnajmi** [comment]
The foundation indeed exists.. and that's about it? Not sure what will happen TBH, but optimistic :)
