### ISSUE TITLE
window/screen Dimensions related issues

### ISSUE THREAD

**Issue by mgcrea** [microsoft/react-native-macos#326]
I've noticed a few issues regarding accessing global window dimensions:

- [`Dimensions.get('window')`](https://reactnative.dev/docs/dimensions) will always return the screen size (should return the window size)
- [`Dimensions.get('screen')`](https://reactnative.dev/docs/dimensions) will throw an error (key not set)
- [`useWindowDimensions`](https://reactnative.dev/docs/usewindowdimensions) will throw (not defined)

**Comment by TheSavior** [comment]
This is hitting us at Facebook as well.

**Comment by tom-un** [comment]
@mgcrea and @TheSavior : I have a fix for this issue here: https://github.com/microsoft/react-native-macos/pull/348

The iOS implementation returns the current key window of the app.   The upstream impl will have to revisit this as it is not UIScene safe.   Maybe it should be returning the dims of the UIWindow that is the ancestor of the RCTRootView as we are doing in macOS.

**Comment by TheSavior** [comment]
Yeah, the upstream API probably needs to be able to change to support multiple windows as right now it seems like it is a global API.

In RN 0.61 (I think it's that version) we introduced a `useWindowDimensions` hook. That API is probably the right choice for making it window specific. Right now that uses Dimensions under the hood, but I think it would be reasonable to change that implementation to work for multiple windows.

**Comment by TheSavior** [comment]
As a concrete proposal, there is a RootViewContext in core, I think `useWindowDimensions` could call something like 

```
const rootTag = useContext(RootTagContext);
const windowDimensions = Dimensions.getForRootView(rootTag)
```

Although I'm not sure what the expected behavior is if the React Native view is embedded in just a smaller piece of the native window. I think normally you'd want the size of the RN root view, but maybe sometimes you want the size of the overall window it is embedded in. I'm not sure what you get on Mobile today, if that is the size of the screen including or excluding native navigation for example.

**Comment by TheSavior** [comment]
> Although I'm not sure what the expected behavior is if the React Native view is embedded in just a smaller piece of the native window.

From the docs for Dimensions https://reactnative.dev/docs/dimensions

> For Android the window dimension will exclude the size used by the status bar (if not translucent) and bottom navigation bar

So it is just the size of the root view, not the overall window. So my proposal seems reasonable at first glance.

**Comment by tom-un** [comment]
On iOS, in .61, that doesn't match the implementation.   It is calling `RCTKeyWindow()` to just get the App's current key window.   Just checked, its still the same in master: https://github.com/facebook/react-native/blob/master/React/UIUtils/RCTUIUtils.m#L18

So on iOS, the 'window' dims will coincidentally be the same as the RCTRootView in many cases (apps made by `react-native init`), but brown field apps or anybody that modifies the base template native code could have an RCTRootView smaller (or bigger 🙀) than the app's UIWindow.   In Microsoft Office *all* our RCTRootView instances are smaller than the app windows.

If the intention of the `Dimensions.get('window')` is to be the size of the root view, then upstream iOS should change to that, and the react-native-macos should change to that.    I guess its analogous to the w3c window objects whose dimension are the tab in the browser, not the browser App window.

**Comment by tom-un** [comment]
As a re-read the thread more carefully, I think we are on the same page: 'window' should return the root view dimensions on all platforms.   I'll modify the react-native-macos PR accordingly.

**Comment by TheSavior** [comment]
I'm not actually sure if that is true...

(more content in this comment to come)

**Comment by tom-un** [comment]
Thanks.   I have similar concerns about breaking existing macOS consumers.   The old behavior never supported 'screen' at all, but it supported 'window' by returning the dimensions of the root view when it could and fell back to the screen if there was no root view.   The safer change in macos is to continue returning the dims of the root view for 'window' when possible.
