### ISSUE TITLE
Overflow hidden property on View not working

### ISSUE THREAD

**Issue by AkshatGiri** [microsoft/react-native-macos#399]
### Issue
Children views overflow parent view even when style property `overflow` is set to `hidden`. 

### Steps to Reproduce

```
<View style={{backgroundColor: 'red', width: 100, height: 100, overflow: 'hidden'}}>
    <View
        style={{
          backgroundColor: 'blue',
          width: 200,
          height: 200,
          opacity: 0.4,
        }}
    />
</View>
```

Child view overflows the bounds of the parent view. 

![image](https://user-images.githubusercontent.com/20054565/82387719-a05cf680-99ec-11ea-9587-4ecf98b4f836.png)

### Expected Behavior

should result in 

![image](https://user-images.githubusercontent.com/20054565/82387752-b8cd1100-99ec-11ea-8fe7-691780d9f44f.png)

**Comment by AkshatGiri** [comment]
needs label `Partner: Facebook`

**Comment by tom-un** [comment]
This is not an easily solvable issue.   Empirically, it is easily fixed by overriding `[UIView clipsToBounds]` to set `self.layer.masksToBounds`.   However, Apple has documented that the behavior is "undefined" to modify the layer's `masksToBounds` property (https://developer.apple.com/library/content/releasenotes/AppKit/RN-AppKit/#10_13Layer-backed%20Views) so although it works in macOS (last tested by me in 10.13.4) it could stop working in a future release.

Internally at Microsoft, we had a scenario that called for overflow:hidden on a View that was masking an Image and Text with a circular mask.   Android also does not support overflow:hidden (or at least it used to not).   Our workaround for Android and macOS was putting the border radius on the Image, and setting the background of the Text to transparent.

Could a similar workaround work for you?

**Comment by sahrens** [comment]
Setting the border radius on the image no longer works after upgrading to 0.61.38 because the `RCTImage` is now a subview of the `RCTView`. We should fix this right away (even if the behavior is technically undefined) since the fix works now and we don't seem to have another options for this critical functionality.

Any idea why this doesn't work out of the box though? Or what the "right way" to solve this is supposed to be?

Also, `overflow: 'hidden'` works on Android, it's just that the implementation is tricky because the Android platform doesn't support it in the same way.

**Comment by appden** [comment]
Should this remain open since #457 was merged?

**Comment by TheSavior** [comment]
It seems like this should be resolved. @akshatgiri feel free to reopen if it still repros
