### ISSUE TITLE
Why do I need to run npx react-native run-macos

### ISSUE THREAD

**Issue by madou** [microsoft/react-native-macos#409]
(I have a few questions sorry)

So back story I'm basically just trying to create a hello world app - you can follow along here https://twitter.com/itsmadou/status/1263229434640740352

One of the things I noticed was I need to run `npx react-native run-macos` to start the app. So of course I think I'm clever - I update the `start` script in `package.json` to that.

```
"start": "npx react-native run-macos"
```

... doesn't work

![image](https://user-images.githubusercontent.com/6801309/82561577-f8475900-9bb6-11ea-9b23-5aeee3b1911e.png)

Question 1) Why does `npx` work but running with `yarn` doesn't?

Also setting up TypeScript needs some extra config - I was going to update the docs here https://github.com/facebook/react-native-website/pull/1945 but apparently it already works and you're using an older version of RN or something 😄 not sure this is my first dive into RN in a long time.

Question 2) Is there a proper way to setup TypeScript or is the way I did it in the above PR the expected way right now?

Question 3) How can I set minimum dimensions to the app frame when it starts up?

**Comment by tom-un** [comment]
Hi.   

Regarding npx not working in a yarn script: it must be due to a workaround that we need to have in place when invoking the CLI.   I went into some detail in Issue #400 about it.   Basically, when invoking the local CLI one must pass a `--use-react-native-macos` argument to the CLI that enables a workaround in `react-native.config.js` (The workaround will go away after we merge in RN .62 Issue #367).   I'm not exactly sure why `yarn` invoked scripts calling `npx` don't but directly calling `npx` does, but you can workaround the issue by changing your `package.json` to invoke the local cli directly, like `"run:macos": "node node_modules/react-native-macos/local-cli/cli.js run-macos"`  

Regarding TypeScript setup: the setup should not be any different that other platforms **except** of course that we are currently at .61 so the latest, greatest presets may not work.   We are working to get up to .62 and later.   You can look at the react-native-community repos such as [WebView](https://github.com/react-native-community/react-native-webview) or [NetInfo](https://github.com/react-native-community/react-native-netinfo) both of which are using react-native-macos *and* are TypeScript based.

The template app generated by react-native-macos-init uses a standard Storyboard for the main window content view and the RCTRootView is constrained to that content view.   You can adjust the window dimensions by adjust the Storyboard settings, or via code in the AppDelegate or ViewController.

**Comment by madou** [comment]
Hi! Thanks for the reply 😄 

Will make the changes for the start script, update the storyboard settings, and wait and see what comes with .62 - cheers!
