### ISSUE TITLE
Trying to use dynamic color causes an unhandled JS exception

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#413]
### Environment

"react-native": "0.62.2",
"react-native-macos": "^0.61.37"
node v14.2.0
yarn 1.22.0
Xcode 11.5
Build version 11E608c

### Issue
I was trying to use dynamic colors in my app, ex:

```
icon: {
    color: {
      dynamic: {
        light: `black`,
        dark: `white`,
      },
    },
  },
```

when saving the file, I got a runtime exception:

Unhandled JS Exception: TypeError: undefined is not an object (evaluating '_reactNative.Appareance.getColorScheme')

I'm guessing this functionality is not implemented yet? 

https://github.com/microsoft/react-native-macos/issues/335 might be related to this issue

(Write your steps here:)

1. Try to use dynamic colors

### Expected Behavior

No crash, actually be able to use colors based on current OS setting
### Actual Behavior

![Screenshot 2020-05-23 at 14 05 34](https://user-images.githubusercontent.com/1634213/82730222-7a8e6500-9cfe-11ea-8649-d2ad32e9c4c6.JPG)

**Comment by tom-un** [comment]
Hi!   The `{dynamic: {light: '', dark: ''} }` color value type does work.   However, the feature was added in this fork back in version 0.59.   Its probable that after merging in .60 and .61 that new color values were added and we failed to refactor them to use the new ColorValue type.

Which `color` prop exactly do you want to use the dynamic color on?   It should not be a problem to add it.

Also, this won't be an on going issue after we merge in react-native 0.63 because I contributed the mechanism upstream as the `PlatformColor` API https://github.com/facebook/react-native/pull/27908.   So after we're in sync with .63, we will no longer be broken by new color props being added upstream.

**Comment by ospfranco** [comment]
Just a background color of a view, if it won't be an issue you can close this ticket and I will test it when  new version is out

**Comment by ospfranco** [comment]
I just tested again, and I must have made an error somewhere because the dynamic notation is working fine, sorry for any confusion
