### ISSUE TITLE
nativeEvent locationY is always equal to pageY

### ISSUE THREAD

**Issue by penx** [microsoft/react-native-macos#418]
### Environment

1. `react-native -v`: 0.62.2
3. `npm ls react-native-macos`: react-native-macos@0.61.37
4. `node -v`: v12.14.1
5. `npm -v`: 6.13.4
6. `yarn --version`: 1.21.1
7. `xcodebuild -version`: Xcode 11.5, Build version 11E608c

### Issue

Event objects have a property 'nativeEvent' which have properties 'locationY', 'pageY'.

My understanding is that [pageY should be the y coordinate of where the user clicked relative to the app window](https://reactnative.dev/docs/view#synthetic-touch-events), wheras locationY is relative to the current component.

However, at the moment, react-native-macos seems to be reporting locationY and pageY to be equal to each other.

### Steps to Reproduce

1. Create a new project, 
2. add several buttons to a page, logging locationY and pageY when a user clicks
3. Click on the buttons and observe logs

```
const App = () => {
  return (
    <>
        
        <Button title="Hi" onPress={e => console.log(e.nativeEvent.locationY, e.nativeEvent.pageY)} />
        <Button title="Hi" onPress={e => console.log(e.nativeEvent.locationY, e.nativeEvent.pageY)} />
        <Button title="Hi" onPress={e => console.log(e.nativeEvent.locationY, e.nativeEvent.pageY)} />
    </>
  );
};
```

### Expected Behavior

I would expect locationY to differ from pageY on the 2nd and 3rd button

### Actual Behavior

locationY and pageY are always the same

**Comment by chrisglein** [comment]
Link to the synthetic touch events didn't resolve for me: Looks like they are in the [0.62 docs](https://reactnative.dev/docs/0.62/view#synthetic-touch-events) but not 0.63, so I assume they were deprecated. Since macOS is on 0.62 that doesn't mean much... but it does mean that if they're slated to go away then you may want to move off of it now?

@NickGerleman did this come up in the Windows merges to 0.63?
@kikisaints do you know what the story is for synthetic-touch-events and if there was an intentional replacement?

**Comment by christophpurrer** [comment]
This issue should have been fixed by https://github.com/microsoft/react-native-macos/pull/1288
