### ISSUE TITLE
ScrollView's onScrollKeyDown doesn't fire in template

### ISSUE THREAD

**Issue by TheSavior** [microsoft/react-native-macos#421]
### Environment

1. `react-native -v`:
3. `npm ls react-native-macos`: react-native-macos@0.61.33 
4. `node -v`:
5. `npm -v`:
6. `yarn --version`:
7. `xcodebuild -version`:

### Issue
In the RNTester app you can use the up and down arrows to navigate between items in a SectionList. In Messenger Desktop's SectionList selecting an element in a ScrollView and then using the up and down arrows doesn't select next items.

Tracking through the code the up and down arrow keys are handled with `onScrollKeyDown` on ScrollView. This isn't firing in Messenger Desktop, and appears to not be firing in a new template app either.

I set a breakpoint in this code:
https://github.com/microsoft/react-native-macos/blob/9232ace99d095a793bddf00ffda3238cc7078820/React/Views/ScrollView/RCTScrollView.m#L1418-L1422

In RNTester, up/down go into the if statement. In the new app template the call goes into the `else`.

![Screen Shot 2020-05-26 at 6 40 05 PM](https://user-images.githubusercontent.com/249164/82966918-cfd9a900-9f80-11ea-92ee-4f8512f8ed08.png)

![Screen Shot 2020-05-26 at 7 17 40 PM](https://user-images.githubusercontent.com/249164/82970660-98b9c680-9f85-11ea-8d51-7734b1093977.png)

From the new app:
```
(lldb) po [[self window] firstResponder]
<RCTView: 0x10383a790; reactTag: 97; frame = {{24, 1}, {432, 90.000999450683594}}; layer = <_NSViewBackingLayer: 0x600000cfe790>>

(lldb) po self
<RCTScrollView: 0x10184ea00; reactTag: 213; frame = {{0, 0}, {480, 270}}; layer = <_NSViewBackingLayer: 0x600000d0cfc0>>
```

From RNTester:
```
(lldb) po [[self window] firstResponder]
<RCTScrollView: 0x102022a00; reactTag: 319; frame = {{0, 55}, {769, 539}}; layer = <_NSViewBackingLayer: 0x600000cbc570>>

(lldb) po self
<RCTScrollView: 0x102022a00; reactTag: 319; frame = {{0, 55}, {769, 539}}; layer = <_NSViewBackingLayer: 0x600000cbc570>>
```

So the issue is that `self == [[self window] firstResponder]` is false in the new app but true in RNTester. I'm not sure yet why the scrollview isn't the firstResponder in the new app.

### Steps to Reproduce

1. Add console.log to `_handleKeyDown` in ScrollView.js
1. Open the new app screen
1. Hit down, expect the callback to be called.

**Comment by tom-un** [comment]
Hi @TheSavior.   The `onScrollKeyDown` event was added for the special case of Lists.   The SectionList in RNTester resembles a native NSOutlineView, NSTableView, or NSContainerView so we made it behave like one.  Such native lists are themselves first responders but the items in these views are typically *not* first responders.   

In the case of RNTester the SectionList can become first responder and is a stop in the key loop.   The items in the list are *not* first responders and individually are *not* part of the key loop.   While the List is first responder `self == [[self window] firstResponder]` and `onScrollKeyDown` events fire as you observed.   The RNTester app logic interprets these events as "change the selected row in the list" which it does.

In the template app, the `<ScrollView>` contains stuff including the `<LearnMoreLinks>` component that renders a bunch of `<TouchableOpacity/>` items which by default can be first responder.   So when one of the links is first responder `[[self window] firstResponder]` is returning that `RCTView` and the parent `<ScrollView>` does not fire `onScrollKeyDown` events.    I can force the template app's `<ScrollView>` to be first responder by modifying `LearnMoreLinks.js` and adding `acceptsKeyboardFocus={false}` to the `<TouchableOpacity>`.

As I said, the `onScrollKeyDown` was made especially for this List scenario and is the reason i named it `onScrollKeyDown` instead of something generic like `onKeyDown`.   If/when we add a generic `onKeyDown` we could make it bubble up and fire without the first responder condition.

**Comment by TheSavior** [comment]
Thanks for the explanation, that is consistent with my understanding as well.

The issue we are having in Messenger is that we have a SectionList with items that are TouchableWithoutFeedback. Tab will go through each element in the section list (which it sounds like it shouldn't from your description). The up and down arrow keys don't do anything. 

I was debugging and got into the scroll view handler which was having a similar behavior as the template app which is why I used that as my minimal repro. Perhaps I need a different minimal repro.

**Comment by tom-un** [comment]
On SectionList you have to add:
`acceptsKeyboardFocus={true}`
`enableSelectionOnKeyPress={true}`
And on TouchableWithoutFeedback items add
`acceptsKeyboardFocus={false}`

**Comment by TheSavior** [comment]
Ah, I got those on sectionlist but didn’t put that prop on the touchable. Okay, I’ll give that a try. I’ll close this out. Thanks for the guidance. It would be great to have some kind of documentation on the Windows / Mac website with this info.

**Comment by TheSavior** [comment]
Yay, that helped!

It looks like every time I hit enter on an item and then use up and down again it starts over from the top of the list. I'd expect it would continue from the selected item in the list. Is there something else I'm missing?

![Screen Recording 2020-06-09 at 11 08 09 PM](https://user-images.githubusercontent.com/249164/84233739-c33c7100-aaa7-11ea-9bb8-0805def47931.gif)
