### ISSUE TITLE
I started to get a UI API called from a background thread: Queue name: com.facebook.react.ShadowQueue,

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#511]
Hi, I need a bit of support here, I'm not sure if I did something, but I think I didn't besides updating the package to the latest versions, and all of the sudden I started getting this warning on app start:

![Screenshot 2020-07-21 at 20 26 45 (2)](https://user-images.githubusercontent.com/1634213/88092485-d8b9b600-cb90-11ea-834b-ec1f45e08b5c.JPG)

I already combed through my app code, I'm sure I'm not using shadows anywhere, and the error is there any time I use a <Text> component, any idea of how to get rid of this?

**Comment by tom-un** [comment]
Hi @ospfranco: it is a legitimate bug in the repo that we make this UI Thread checker assert if a RCTDynamicColor is used.   But it should only be encountered if a color prop is assigned a dynamic value, e.g. `color: { dynamic: { light: 'black', dark: 'white' } }`.   Do you explicitly use a dynamic color in your app?   Otherwise none of the built-in components should use a dynamic color.   The RNTester does, but that shouldn't impact your code.

**Comment by ospfranco** [comment]
Yes, I do, and extensively it is necessary to have consistent color schemes to pass apple's app review guidelines

**Comment by tom-un** [comment]
Ok.   We need to fix it.    Upstream, for iOS, we are able to implement dynamic colors using [UIColor initWithDynamicProvider](https://developer.apple.com/documentation/uikit/uicolor/3238041-initwithdynamicprovider?language=objc).  The macOS NSColor originally did not have an equivalent so we made this RCTDynamicColor.   In macOS 10.15 and later there *is* now a [NSColor colorWithName:dynamicProvider:](https://developer.apple.com/documentation/appkit/nscolor/3294481-colorwithname?language=objc) that looks promising -- so we could use it if running on 10.15 or later and fallback to RCTDynamicColor otherwise.

**Comment by Saadnajmi** [comment]
I would actually like to keep this bug and open. I was not aware that there _was_ a way to make Dynamic Colors thread safe. With RN-macOS 0.66, we are bumping the minimum to 10.15 so this might actually be a good solution.

**Comment by Saadnajmi** [comment]
This should be fixed with the latest RN-macOS 0.66.13 +
