### ISSUE TITLE
'Question: NodeJS modules'

### ISSUE THREAD

**Issue by jet8a** [microsoft/react-native-macos#521]
Is it possible to use nodeJS modules? For example https://www.npmjs.com/package/run-applescript

**Comment by tom-un** [comment]
nodeJS modules that are pure JavaScript can sometimes work in react-native projects.   For example, I was able to use https://www.npmjs.com/package/@microsoft/microsoft-graph-client in a react-native project because the JS in that package only makes core JavaScript calls and XHR calls.   But if the package makes any Node calls, like `exec` or `execa`, then no, they will not work in any react-native project on any platform.

The https://www.npmjs.com/package/run-applescript will *not* work because its uses Node's `execa` api to spawn `osascript`.

**Comment by Angelk90** [comment]
@tom-un : If I want to run a sh script, with react native on macos, what can I do?
