### ISSUE TITLE
'Question: Is it possible to use React Native for the following app?'

### ISSUE THREAD

**Issue by harshayburadkar** [microsoft/react-native-macos#527]
I am good at developing web applications and am seriously considering React Native to develop a desktop app (mainly for MacOS currently, Windows may be in the future).

It is a simple app with 2 to 3 pages. But in addition to the pages, there are a few requirements that I am unsure if a React Native app can have:
- custom Siri commands (SiriKit?) that initiate certain actions within the app and bring the app to focus
- an icon in the menu bar which changes depending on what website is in focus in the browser
- when clicking the icon in the menu bar, I would like to have a popup menu
- this icon in the menu bar should stay even in the menu bar even if the app is not open

If not directly supported by React Native - can I write native code in Swift just for these specialized requirements and still use React Native for the rest?
Kindly advise if I should use React Native for this scenario.

**Comment by HeyImChris** [comment]
There's no requirement that if part of your app is in React-Native then the entire app uses React-Native. A single view can be a React-Native instance and you can use native Swift/Obj-C elsewhere.

There's nothing that directly works with SiriKit in React-Native yet. I haven't worked with SiriKit before but it sounds like there's not much UI? You're probably just as well off using native code to marshal those interactions.

Regarding the menu bar, there's no custom menu bar support for macOS as it was built out to be in parity with iOS. We welcome open source contributors to add new/missing components though! Using native code, NSMenuItems don't directly support having buttons or other interactive views in them so you'll likely need to create an NSMenuItem and override the `view` prop to contain whatever you need.

I'm not sure what you mean about an icon staying in the menu bar even when the app is not open. Each app has its own instance of the menu bar that you have control over, but due to sandboxing I don't think you'll be able to add an item to the generic Finder menu bar you'd see with no apps open.

**Comment by harshayburadkar** [comment]
`There's no requirement that if part of your app is in React-Native then the entire app uses React-Native. A single view can be a React-Native instance and you can use native Swift/Obj-C elsewhere.`

Is there any guidance around doing this? Like a tutorial or something similar. Also how to manage the code and release packaging of this, etc.

`There's nothing that directly works with SiriKit in React-Native yet. I haven't worked with SiriKit before but it sounds like there's not much UI? You're probably just as well off using native code to marshal those interactions.
`
I understand that for SiriKit you need to [create an Intents App Extension](https://developer.apple.com/documentation/sirikit/creating_an_intents_app_extension). So how would we go about adding an accompanying Intents App Extension along with the RN app?


`I'm not sure what you mean about an icon staying in the menu bar even when the app is not open. Each app has its own instance of the menu bar that you have control over, but due to sandboxing I don't think you'll be able to add an item to the generic Finder menu bar you'd see with no apps open.`
I mean something like Evernote - even if you quit the application from the Dock. The Evernote icon stays in the menubar and still has some quick functionality available there. It may be something similar to an extension which is separate from the actual app. I am not entirely sure but I know that it gets installed with Evernote itself and is not something I added separately.

**Comment by HeyImChris** [comment]
You can look at the RNTester test app to see how we load the desired bundle and insert it into a view. It's very similar to how react-native works for iOS so I'd recommend going through Facebook's [Getting Started](https://reactnative.dev/docs/getting-started) which is rife with analogous information for how it works on iOS.

As for react-native-macos release cycles, there isn't a consistent cadence yet, but we're working on scheduling a more formal way of doing this that better aligns with upstream react-native.

Regarding using Intents App Extensions, from reading the documentation it looks like it only exists on macOS via Catalyst (but again I've never actually used them before). You can communicate between any native code (e.g. SiriKit related info) and JS the same way you would for an iOS React-Native app so I think going through Facebook's getting started docs will help ramp up there.

For the menu bar issue you'd be best off asking on stack overflow. That seems like a more generic macOS app question that isn't related to React-Native as RN doesn't have menu bar support so that'd need to be native in your app anyway.

**Comment by HeyImChris** [comment]
Downloaded Evernote and I misunderstood what you meant by leaving an icon in the menu bar. On the right there's the status items which I'm guessing is what you're talking about as I now see an Evernote icon there. There's no direct RN support for those so you'll have to implement it natively, typically in your app delegate. There are tutorials on how to do this such as this [one](https://www.appcoda.com/macos-status-bar-apps/)

**Comment by harshayburadkar** [comment]
`Regarding using Intents App Extensions, from reading the documentation it looks like it only exists on macOS via Catalyst (but again I've never actually used them before). `
Yes, indeed I found out later that night after my last reply that SiriKit isn’t yet made available for MacOS. That feature is going to have to wait.

For the rest of the parts thanks a lot for the detailed inputs - I will check it out and the tutorial as well.
I am excited how RN develops for these new platforms. 🚀 🤟

**Comment by HeyImChris** [comment]
Great to hear, always happy to help. Sounds like we can close this issue for now.
