### ISSUE TITLE
Issues after app migration to 0.62 prerelease

### ISSUE THREAD

**Issue by Simek** [microsoft/react-native-macos#553]
### Environment

1. `react-native -v`: 0.62.2
3. `npm ls react-native-macos`: 0.62.0-prerelease.6
4. `node -v`: 14.7.0
5. `npm -v`: 6.14.4
6. `yarn --version` 1.22.4
7. `xcodebuild -version`: 11E708

### Issue

1. I had to rename `Folly` pod to [`RCT-Folly`](https://github.com/microsoft/react-native-macos/blob/master/third-party-podspecs/RCT-Folly.podspec) which is not a part of the unforked RN update guide:
    * https://react-native-community.github.io/upgrade-helper/?from=0.61.5&to=0.62.2
    * https://raw.githubusercontent.com/react-native-community/rn-diff-purge/release/0.62.2/RnDiffApp/ios/Podfile

2. I was not able to build the app because of missing header file in [RCTRedBox.mm#L17](https://github.com/microsoft/react-native-macos/blob/master/React/CoreModules/RCTRedBox.mm#L17):
```[...]/react-native-macos/React/CoreModules/RCTRedBox.mm:17:9: 'React/RCTRedBoxExtraDataViewController.h' file not found```

    Those files are exclusively excluded for macOS [React-Core.podspec#L66](https://github.com/microsoft/react-native-macos/blob/master/React-Core.podspec#L66), but this change was a part of `0.61` which was building and working as expected for me. 

    Removing the exclusion from the `podspec` locally and reinstalling pods won't fix the issue.

3. After removing or commenting out the code parts related to the `RCTRedBoxExtraDataViewController` from the `RCTRedBox.mm` Xcode failed to launch the Metro bundler because of missing permissions:
<img width="432" alt="Screenshot 2020-08-19 at 17 58 02" src="https://user-images.githubusercontent.com/719641/90660061-b7a6bc80-e245-11ea-863c-b4813584ce5f.png">

`chmod +X launchPackager.command` won't help, I had to use `chmod 777 launchPackager.command`.

4. The same permission problem occurred with `react-native-xcode.sh` script:
```/[...]/macos/DerivedData/Reminders/Build/Intermediates.noindex/Reminders.build/Debug/Reminders-macOS.build/Script-381D8A6E24576A4E00465D17.sh: line 3: ../node_modules/react-native-macos/scripts/react-native-xcode.sh: Permission denied```

After dealing with all the issues listed above locally I was able to build and run app using `0.62` prerelease version 🙂 

### Steps to Reproduce

1. Clone `https://github.com/Simek/react-native-macos-reminders.git`
2. Switch to `0.62` branch
3. Open `macos/Reminders.xworkspace` in Xcode
4. Build or launch the app

### Expected Behavior

Build succeeded and app running without issues (like on `0.61`).

### Actual Behavior

Build fails.

### Reproducible Demo

* https://github.com/Simek/react-native-macos-reminders

### Additional context

AMA

**Comment by Simek** [comment]
@chrisglein Not a problem, I'm happy to help and this sample app is just my test workbench, no worries. 

FYI I have asked on Discord if I should put the issue for the prerelease on GitHub, @acoates-ms recommended me to do so.

**Comment by alloy** [comment]
Thanks a lot, @simek! I’ll go through these steps tomorrow.

**Comment by tom-un** [comment]
@alloy + @Simek : regarding the executable bit missing on the `launchPackager.command`.   This is an old issue in this repo: either because the fork was created on a Windows machine originally, or because git operation continue to happen on Windows machines, the unix permission bits get stripped.   Our workaround is a `yarn` post install step.   Somehow in the 62 merge the postInstall step got removed.   It just needs to be added back in `packages.json`'s `"scripts": {`:
```json
    "postinstall": "node scripts/postInstall.js"
```
it will restore the executable bit on all scripts: `.sh`, `.command`, etc.

**Comment by acoates-ms** [comment]
We should be able to move the main publish job to the ubuntu image now.  -- Strangely we are doing the internal publish on ubuntu, but the npmjs one on windows.   -- Its cleaner to do the chmod before publishing instead of having the postInstall script.

**Comment by alloy** [comment]
@simek Thanks again for your assistance! 🙏  After spending some time on it today I was able to fix the issues and get the app running.

* Fixed a few issues in [this PR](https://github.com/microsoft/react-native-macos/pull/560).
* You should update the deployment target setting in `rn-macos-popover.podspec`, otherwise it fails to recognise the entry and will default to `10.6`—which will fail to build files that treat libdispatch types as objc objects, see `OS_OBJECT_USE_OBJC `.

  ```diff
  -   s.platforms    = { :macos => "10.14" }
  +   s.platforms    = { :osx => "10.14" }
  ```

----

I also distilled the following upgrade instructions:

# Upgrade steps

1. Bump dependencies: `yarn add 'react@16.11.0' 'react-native@0.62.2' 'react-native-macos@0.62.0'`
1. In `macos/Podfile` replace these:

   ```
   pod 'ReactCommon/jscallinvoker', :path => '../node_modules/react-native-macos/ReactCommon'
   pod 'Folly', :podspec => '../node_modules/react-native-macos/third-party-podspecs/Folly.podspec'
   ```
   with:
   ```
   pod 'ReactCommon/callinvoker', :path => '../node_modules/react-native-macos/ReactCommon'
   pod 'RCT-Folly', :podspec => '../node_modules/react-native-macos/third-party-podspecs/RCT-Folly.podspec'
   ```

**Comment by Simek** [comment]
@alloy Thank you for addressing those issues!

> You should update the deployment target setting in rn-macos-popover.podspec, otherwise it fails to recognise the entry and will default to 10.6—which will fail to build files that treat libdispatch types as objc objects, see OS_OBJECT_USE_OBJC .

And thank you for the hint, it is my experimental native module and I do not have much experience in this field. 🙏
