### ISSUE TITLE
Support react-native-document-picker

### ISSUE THREAD

**Issue by shahthepro** [microsoft/react-native-macos#651]
# Support `react-native-document-picker`
## Basic Info
* Module Repo URL: https://github.com/Elyx0/react-native-document-picker
* Target version: 4.0.0
* [ ]  Issue exists on module repo (if so, link)

## Overview of Required Functionality
Need to add support for the npm package so that it can work with the latest version of react-native-macos.

## Essential Features
- Selecting files by type
- Selecting single or multiple files
- Reading contents and metadata of selected files
- Writing back to opened files

**Comment by kevinvangelder** [comment]
Support for new platforms is a responsibility of the module, not the platform. I would suggest creating an issue on that repo or implementing it yourself.

**Comment by chrisglein** [comment]
Correct, the work would need to happen in that repo. Definitely open a issue there as well. The template on this repo is to track requests for macOS support so that there's a place where people can look for which modules are being asked for for macOS as it's a small list relative to [all possible modules](https://reactnative.directory/) (862 right now)
