### ISSUE TITLE
Hermes is unstable

### ISSUE THREAD

**Issue by ospfranco** [microsoft/react-native-macos#686]
### Environment

react-native-macos: 0.63.4
"hermes-engine-darwin": "^0.5.3",

### Issue

I was using hermes on my app and releasing it to customers, but I got feedback that the app would randomly hang and consume 100% of one processor, I tried debugging my code but I could not find a problem.

Fast forward a week, I was developing some feature today and started experiencing the same issue, I pretty much deconstructed the entire app until bare bones but no error was thrown and code was correct, after a while and connected the debugger and js started running on chrome and all of the sudden the problem was gone.

I'm sorry but I could not find any way to reproduce the issue, it was solved by getting rid of hermes and reverting back to jscore, there everything works as expected with the same code...

**Comment by chrisglein** [comment]
Have you tried looking for similar issues on the [hermes repo](https://github.com/facebook/hermes)? Mainly this macOS repo just sets up the ability to consume Hermes (not yet the default), so more fine-grained support should go to where Hermes lives. And it's not on by default because we're still looking to have most issues like this ironed out first.

Closing out this issue because I don't think there's anything to act on from the macOS side without a dedicated repro. Hopefully the Hermes repo is helpful.
