### ISSUE TITLE
Drawer Navigator addListener error on react native macOs

### ISSUE THREAD

**Issue by Ngomana** [microsoft/react-native-macos#687]
### Environment

1. `react-native -v`:
3. `npm ls react-native-macos`: react-native-macos@0.63.4 
4. `node -v`: v12.16.3
5. `npm -v`: 6.14.8
6. `yarn --version`: 1.22.5
7. `xcodebuild -version`:Xcode 12.3 Build version 12C33

createDrawerNavigator not usable in react-native-window/macos (I test with macos)

Expected Behavior

Should be usable.

How to reproduce
Basic nested Stack => Drawer, or even just Drawer alone will cause the error.

Use the code below and click "DrawerStack"
```
const Home = ({navigation}) => (
  <View style={{flex: 1}}>
    <Button
      onPress={() => navigation.navigate('DrawerStack')}
      title="DrawerStack"
    />
  </View>
);

const DrawerScreen = ({navigation}) => (
  <View style={{flex: 1}}>
    <Button onPress={() => {}} title="Drawer" />
  </View>
);

const Drawer = createDrawerNavigator();
const DrawerStack = ({navigation}) => (
  <Drawer.Navigator initialRouteName="DrawerScreen">
    <Drawer.Screen name="DrawerScreen" component={DrawerScreen} />
  </Drawer.Navigator>
);

const App = () => (
  <SafeAreaProvider>
    <NavigationContainer theme={DarkTheme}>
      <Stack.Navigator initialRouteName="Home">
        <Stack.Screen name="Home" component={Home} />
        <Stack.Screen name="DrawerStack" component={DrawerStack} />
      </Stack.Navigator>
    </NavigationContainer>
  </SafeAreaProvider>
);

export default App;
```
![Screenshot 2021-01-07 at 09 36 13](https://user-images.githubusercontent.com/61317733/103864757-d231e300-50cb-11eb-9d9d-89cb9334c75f.png)

**Comment by chrisglein** [comment]
@Ngomana I'm guessing you're using the [navigation module](https://github.com/react-navigation/react-navigation)? You didn't mention that in your repro, but I assume since you're talking about drawer and navigation that that's what you're using. If there's an issue with that module then you should report it against [that repo](https://github.com/react-navigation/react-navigation) as that's likely where the fix is, unless it seems to be an issue with macOS's core platform implementation.
