### ISSUE TITLE
Track macOS specific changes that differ from upstream

### ISSUE THREAD

**Issue by HeyImChris** [microsoft/react-native-macos#774]
### Issue

There are a lot of diffs between this fork and Facebook's upstream repository that we need to track to make things like merges easier. Currently, these issues are tracked and tagged with a Microsoft internal bug number. Using this bug number doesn't make much sense now that we're in open source so this issue can be referenced to track purposeful differences, fixes, and improvements that we've made in our repo.

For many of the issues tagged with this (i.e. the non-macOS specific ones), the goal is that they can be moved upstream to Facebook's repo.

**Comment by huperniketes** [comment]
Can someone let me know the status of these GH#774 tags in the code? They appear to present the possibility of method not found (RCTRedBox, line 463), (RCTDevMenu, line 108) exceptions, among other things, at runtime.

These two in particular interest me because, as a JS/TS/React/React-Native noob, I'm encountering the red box quite often; and if resolving stalled fixes can improve my debugging productivity, I'd like to help move them along by golly, ya betcha.

**Comment by Saadnajmi** [comment]
They're meant as a generic marker of "This is where we differ from React Native Core". Sometimes we stub out iOS code that doesn't work on macOS, sometimes we add an ifdef for iOS/macOS code, sometimes we're extending a `Platform.OS` check. There isn't an answer for the status of individual tags. If there are specific ones that could be fixed / moved upstream / seem wrong (you seem to mention RCTDevMenu), feel free to open issues about them :)

**Comment by huperniketes** [comment]
Thanks. Will do.
