### ISSUE TITLE
Drag & Drop support

### ISSUE THREAD

**Issue by rborn** [microsoft/react-native-macos#842]
# Proposal: Drag and drop support for any type of content

## Summary
Having the possibility to do drag/drop any type of content over an RNM app would open many possibilities for developers.
This is an example - https://ospfranco.com/messer (not mine) where you can simply drag an image over the menu (tray?) app and the image gets converted right away

## Motivation

I have 2 functionalities in mind, one is the above - drag  an image and take an action over it, and something similar to https://ray.so/ but in a menu app

## Open Questions

I believe the best way is to support any type of content being dropped to the target and so we are not limited in what we can use it for :)
Also to work with both on the window app and menu(tray)

Thank you ❤️

**Comment by ospfranco** [comment]
haha nice to see there are people inspired by my work, in any case, Messer already had a code syntax highlighter, but I removed it, because it is clunky to edit it from a menu bar app (and also the market is super niche)

In any case, you can implement the same functionality as messer in an RN-macOS app without too much trouble, the only missing functionality is dragging outside of the app

**Comment by HeyImChris** [comment]
This support would be awesome. It looks like we don't have Windows support for this either and we'd want to align APIs on Desktop before making contributions to either, but enhancements are always welcome assuming we have a good cross-plat architecture.

**Comment by plufz** [comment]
@rborn I would really like to be able to do this as well, my app depends on it. Do you mean that you can simply onDragEnter on a TouchableOpacity component and then drag a file from finder to that component in your app app? I tried the code below and nothing happens. Any pointers would be highly appreciated.

```
<View>
<TouchableOpacity
            onDragEnter={() => {
              alert('drag enter');
            }}
            onDragLeave={() => {
              alert('drag leave');
            }}
            onDrop={() => {
              alert('drop');
            }}
          >
            <Text>Press Here</Text>
          </TouchableOpacity>
</View>
```

**Comment by rborn** [comment]
@plufz you need to add the `draggedTypes`  prop 
```
 <TouchableOpacity
              draggedTypes={["fileUrl"]}
              onDrop={(e) =>
                  console.log("od", e.nativeEvent.dataTransfer?.files?.[0])
              }
...
```

I didn't have the time to research more  how these types actually work and I couldn't make it work with folders. If you find anything let me know :)

**Comment by ospfranco** [comment]
ok, so I was trying to re-write messer on RN (because I got tired of SwiftUI) but dragging out is not working for me, which kinda kills this idea on the water, that being said, here are some pointers for those of you looking to implement something like I did

You won't get drag&drop support on the Menu bar from RN, RN exists only within the RCTRootView you embed in an NSWindow, that being said, adding this to an RN app is simple, the native code goes something like this:

```swift
// Register draggable types
var registeredDraggedTypes: [NSPasteboard.PasteboardType] = [.fileURL]

let filePromiseReceiverTypes = NSFilePromiseReceiver.readableDraggedTypes.map {
  NSPasteboard.PasteboardType($0)
}

registeredDraggedTypes.append(contentsOf: filePromiseReceiverTypes)

// register a button on the macOS MenuBar
if let button = self.statusBarItem.button {
  button.imagePosition = NSControl.ImagePosition.imageLeft
  button.image = NSImage(named: "StatusBarIcon")
  button.action = #selector(togglePopover(_:))
  button.registerForDraggedTypes(registeredDraggedTypes)
}
```

The types are macOS extensions, `.fileURL` only works for file system... err files, but you can drag and drop lots of different stuff, for example, dragging and dropping directly from a browser image requires a `PNG` or `.filePromise` types (`.filePromises` are another funny topic), you can also drag&drop strings (`.string`) and so on

Afterward, you can send an event to RN that a file has been dropped (you probably want to copy the file in native code to the app sandbox folder), if you want a more detailed tutorial I covered how to do this in my [RN-macOS course](https://www.newline.co/courses/building-react-native-apps-for-mac)

-----------------

Back to my original problem, dragging out doesn't seem to be working for me, also bear in mind, for drag out to work nicely with macOS, one needs to provide a native UI representation that macOS takes over and helps the user drag out the "item"

As stated by @chrisglein , this are very different use cases between in-app dragging and native/OS dragging, would be cool to see this working properly

**Comment by plufz** [comment]
> The types are macOS extensions, `.fileURL` only works for file system... err files, but you can drag and drop lots of different stuff, for example, dragging and dropping directly from a browser image requires a `.png` or `.filePromise` types (`.filePromises` are another funny topic), you can also drag&drop strings (`.string`) and so on

Thanks for all this info on macos drag and drop. Do you know how much work it would be to implement support for dropping non-files to a normal RN window (not a menu app)? From what I can tell only "fileUrl" is supported as draggedtypes today (adding for example "png" to the array did nothing for me and from what I can tell in RN source code only fileUrl is supported).

**Comment by ospfranco** [comment]
I'm a complete noob when it comes to RN(-macOS) internals, also like I said, `.filePromise` requires some deep integration with the macOS APIs which might not be easily adjustable to all OSes RN supports nowadays... a proper maintainer should answer this

**Comment by ospfranco** [comment]
For those interested, I managed to get a draggable image working:

https://twitter.com/ospfranco/status/1482649412396584962?s=20

Here is a gist with the internal code of the image component

https://gist.github.com/ospfranco/f2a74edcc191ac264339032b3a1344da

Until rn-macos provides this functionality natively, doing it yourself is the easiest
