### ISSUE TITLE
Setting UIUserInterfaceStyle does not effect appearance.

### ISSUE THREAD

**Issue by jbcullis** [microsoft/react-native-macos#911]
### Environment

```markdown
react-native 0.64.0:
npm ls react-native-macos: 0.64.13
node: 17.0.1
npm: 8.1.0
yarn: N/A
xcodebuild: 13A1030d
```

### Steps to reproduce the bug

Set UIUserInterfaceStyle in info.plist to 'Light' but it doesn't override dark mode.

### Expected Behavior

Force light mode

### Actual Behavior

No effect on appearance.

**Comment by HeyImChris** [comment]
UIUserInterfaceStyle only works on iOS. Given that, can you verify if this is a bug with FB's [upstream repo](https://github.com/facebook/react-native) and if so, file the bug there instead of here?

**Comment by jbcullis** [comment]
I'm still researching this one @HeyImChris - Looks like UIUserInterfaceStyle is available in Catalyst.
Ideally, there would be a way of opting out of dark mode globally. Having to set the color attribute everywhere is a bit painful.

**Comment by Saadnajmi** [comment]
Closing as this is more of a macOS app development issue, rather than a React Native macOS issue. If one wanted to adopt dark mode everywhere, they'd probably have to modify their App Delegate to set the NSApplication appearance or do something else listed here: https://developer.apple.com/documentation/uikit/appearance_customization/supporting_dark_mode_in_your_interface?language=objc

**Comment by Saadnajmi** [comment]
Just a note, as part of React Native 0.72, there's a new method `setColorScheme` exposed off of Appearance: https://github.com/facebook/react-native/pull/36122

Once we release React Native 0.72, we should have support for that as well.
